name: Regression Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'dts/**'
      - 'tests/**'
      - 'pixi.toml'
      - 'pixi.lock'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'dts/**'
      - 'tests/**'
      - 'pixi.toml'
      - 'pixi.lock'

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest
          cache: true
          
      - name: Run Regression Tests
        run: pixi run test
